### ISSUE TITLE
Can background image full fill behind Taskbar?

### ISSUE THREAD

**Issue by icharge** [AlexanderPro/AwesomeWallpaper#3]
I made Taskbar as transparency but still see original background image. So can you fill this gap with new background image/video ?

**Comment by AlexanderPro** [comment]
Hi, icharge

I have fixed it in [this version v1.0.5](https://github.com/AlexanderPro/AwesomeWallpaper/releases/download/v1.0.5/AwesomeWallpaper_v1.0.5.zip)

**Comment by icharge** [comment]
Thank you

![image](https://user-images.githubusercontent.com/1619007/72593892-bbcdcd00-3938-11ea-880b-9fa209a7a4ab.png)
