### ISSUE TITLE
GetDriveTotalSize & GetDriveFreeSpace errors

### ISSUE THREAD

**Issue by astroboots** [AlexanderPro/AwesomeWallpaper#4]
**~AwesomeWallpaper\Utils\SystemInformationUtils.cs**
`public static string GetDriveTotalSize(DriveInfo driveInfo)`
`public static string GetDriveFreeSpace(DriveInfo driveInfo)`

Fails on attempting to get drive size of my bluray drive. I've temporarily worked around this with a try catch and returning "0" on the exception.

**Comment by AlexanderPro** [comment]
Hi astroboots,

Please, try this version [1.0.6](https://github.com/AlexanderPro/AwesomeWallpaper/releases/download/v1.0.6/AwesomeWallpaper_v1.0.6.zip)

— Regards, Alexander Illarionov

**Comment by astroboots** [comment]
That seems to have resolved the issue. Thank you.
